name-template: "$RESOLVED_VERSION"
tag-template: "release/$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

categories:
  - title: "ðŸš€Features"
    labels:
      - "pr-type: feature"
  - title: "ðŸ›BugFixes"
    labels:
      - "pr-type: bugfix"
  - title: "ðŸ§¯HotFixes"
    labels:
      - "pr-type: bugfix"
  - title: "ðŸ”§Chore"
    labels:
      - "pr-type: chore"

autolabeler:
  - label: "pr-type: feature"
    branch:
      - '/feature\/.+/'
    title:
      - "/feature/i"
  - label: "pr-type: bugfix"
    branch:
      - '/bugfix\/.+/'
    title:
      - "/bugfix/i"
  - label: "pr-type: hotfix"
    branch:
      - '/hotfix\/.+/'
    title:
      - "/hotfix/i"
  - label: "pr-type: chore"
    branch:
      - '/chore\/.+/'
    title:
      - "/chore/i"

version-resolver:
  major:
    labels:
      - "version-up: major"
  minor:
    labels:
      - "version-up: minor"
  patch:
    labels:
      - "version-up: patch"
  default: patch

template: |
  ## Changes
  $CHANGES
