name-template: "$RESOLVED_VERSION"
tag-template: "release/$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

categories:
  - title: "🚀Features"
    labels:
      - "pr: feature"
  - title: "🐛BugFixes"
    labels:
      - "pr: bugfix"
  - title: "🧯HotFixes \n> [!WARNING]\n> hotfixを含むリリースのリリースノートにはリリースに含まれるPRが記載されていない場合があります。\n> Publish する際に `Generate release notes` 等でリリースノートを編集してください。"
    labels:
      - "pr: hotfix"
  - title: "🔧Chore"
    labels:
      - "pr: chore"
      - "dependencies" # dependabot の PR

autolabeler:
  - label: "pr: feature"
    branch:
      - '/feature\/.+/'
    title:
      - "/feature/i"
  - label: "pr: bugfix"
    branch:
      - '/bugfix\/.+/'
    title:
      - "/bugfix/i"
  - label: "pr: hotfix"
    branch:
      - '/hotfix\/.+/'
    title:
      - "/hotfix/i"
  - label: "pr: chore"
    branch:
      - '/chore\/.+/'
    title:
      - "/chore/i"

version-resolver:
  major:
    labels:
      - "version-up: major"
  minor:
    labels:
      - "version-up: minor"
  patch:
    labels:
      - "version-up: patch"
  default: patch

template: |
  ## Changes

  $CHANGES
