name-template: "$RESOLVED_VERSION"
tag-template: "release/$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

categories:
  - title: "🚀Features"
    labels:
      - "pr-type: feature"
      - "feature"
  - title: "🐛BugFixes"
    labels:
      - "pr-type: bugfix"
      - "bugfix"
  - title: "🧯HotFixes \n> [!WARNING]\n> hotfixを含むリリースのリリースノートにはリリースに含まれるPRが記載されていない場合があります。\n> Publish する際に `Generate release notes` 等でリリースノートを編集してください。"
    labels:
      - "pr-type: hotfix"
      - "hotfix"
  - title: "🔧Chore"
    labels:
      - "pr-type: chore"
      - "chore"
      - "dependencies" # dependabot の PR

autolabeler:
  - label: "pr-type: feature"
    branch:
      - '/feature\/.+/'
    title:
      - "/feature/i"
  - label: "pr-type: bugfix"
    branch:
      - '/bugfix\/.+/'
    title:
      - "/bugfix/i"
  - label: "pr-type: hotfix"
    branch:
      - '/hotfix\/.+/'
    title:
      - "/hotfix/i"
  - label: "pr-type: chore"
    branch:
      - '/chore\/.+/'
    title:
      - "/chore/i"
  # - label: "feature"
  #   branch:
  #     - '/feature\/.+/'
  #   title:
  #     - "/feature/i"
  # - label: "bugfix"
  #   branch:
  #     - '/bugfix\/.+/'
  #   title:
  #     - "/bugfix/i"
  # - label: "hotfix"
  #   branch:
  #     - '/hotfix\/.+/'
  #   title:
  #     - "/hotfix/i"
  # - label: "chore"
  #   branch:
  #     - '/chore\/.+/'
  #   title:
  #     - "/chore/i"

version-resolver:
  major:
    labels:
      - "VersionUp/major"
  minor:
    labels:
      - "VersionUp/minor"
  patch:
    labels:
      - "VersionUp/patch"
  default: patch

template: |
  ## Changes

  $CHANGES
